version: "3"
services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - data_db:/data/db

  server:
    image:
    ports:
      - 3000:3000
    depends_on:
      - mongo
    links:
      - mongo:mongo
